spring:
  application:
    name:junw-pao-server
  # 指定运行环境
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/junw_pao?characterEncoding=utf-8&&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: 123456
  # 登录过期时间 s
  session:
    timeout: 86400
  # redis 配置
  data:
    redis:
      port: 6379
      host: localhost
      password: passed
      database: 0

      # Lettuce 客户端的配置
      lettuce:
        # 连接池配置
        pool:
          # 最小空闲连接
          min-idle: 0
          # 最大空闲连接
          max-idle: 8
          # 最大活跃连接
          max-active: 8
          # 从连接池获取连接 最大超时时间，小于等于0则表示不会超时
          max-wait: -1ms
server:
  port: 8080
  servlet:
    context-path: '/api'
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启控制台打印日志