spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/junw_pao?characterEncoding=utf-8&&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: 123456
  # 登录过期时间 s
  session:
    timeout: 86400

server:
  address: 0.0.0.0

# swagger-ui TODO 上线注意修改swagger配置，避免暴露接口
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    path : /swagger-ui.html
    enabled: false
  packages-to-scan: my.junw.pao.controller